services:
  - type: web
    name: mediconnect-web
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: mediconnect-db
          property: connectionString
  
databases:
  - name: mediconnect-db
    databaseName: mediconnect
    plan: free